name: misskey master - Build and Push

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: misskey-dev/misskey
          ref: master
          
      - name: Get Version
        run: |
          echo "ver=$(cat package.json | jq -r .version)" >> $GITHUB_ENV
          
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.actor }}/misskey
          flavor: latest=auto
          tags: |
            type=sha,enable=true
            type=sha,format=long
            type=raw,value=latest,enable=${{ github.event_name == 'release' }}
            type=raw,value=${{ env.ver }}
            
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          outputs: >-
            type=image,
            name=target,
            annotation-index.org.opencontainers.image.description=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.description'] }},
            annotation-index.org.opencontainers.image.source=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.source'] }},
            annotation-index.org.opencontainers.image.licenses=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.licenses'] }}
