name: develop - Build and Push

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          repository: misskey-dev/misskey
          ref: develop
      -
        name: Get Version
        run: |
          echo "ver=$(cat package.json | jq -r .version)-$(git show --format="%h2" --no-patch)" >> $GITHUB_ENV
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/misskey-develop:latest
            ghcr.io/${{ github.repository_owner }}/misskey-develop:${{ env.ver }}

